---
swagger: "2.0"
info:
  version: "1.0.0"
  title: "Rest api Korchemnyi"
host: "com.learning.store"
basePath: "/src"
schemes:
  - "http"
paths:
  /products:
    post:
      tags:
        - "item"
      summary: "Add new product"
      description: ""
      operationId: "additem"
      consumes:
        - "application/json"
        - "application/xml"
      produces:
        - "application/xml"
        - "application/json"
      responses:
        405:
          description: "Invalid input"
      security:
        - petstore_auth:
            - "write:products"
            - "read:products"
    put:
      tags:
        - "item"
      summary: "Update product"
      description: ""
      operationId: "updateItem"
      consumes:
        - "application/json"
        - "application/xml"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Pet object that needs to be added to the store"
          required: true
          schema:
            $ref: "#/item"
      responses:
        400:
          description: "Invalid ID supplied"
        404:
          description: "Pet not found"
        405:
          description: "Validation exception"
      security:
        - petstore_auth:
            - "write:items"
            - "read:items"
